# Generated by Django 3.2.9 on 2022-01-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('FUNDACJA', 'fundacja'), ('ORGANIZACJA POZARZĄDOWA', 'organizacja pozarządowa'), ('ZBIÓRKA LOKALNA', 'zbiórka lokalna')], default='FUNDACJA', max_length=35)),
                ('categories', models.ManyToManyField(to='oddaj_w_dobre_rece_app.Category')),
            ],
        ),
    ]
